### ISSUE TITLE
Failing python3.7 - linux

### ISSUE THREAD

**Issue by martindurant** [conda-forge/google-auth-oauthlib-feedstock#5]
Anyone know why 0.2.0 is not building on linux? This is the only version for python 3.7 (because of timing). Indeed, it looks as if this library should be noarch anyway...

**Comment by martindurant** [comment]
For reference, the build logs don't even seem to start making the package: could a simple re-render fix it?

**Comment by cpcloud** [comment]
I'm also hitting this issue: https://circleci.com/gh/cpcloud/ibis/15143?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@tswast @jreback Can one of you try re-rendering or adding me as a maintainer and I'll rerender?

**Comment by mariusvniekerk** [comment]
Is this still an issue?

**Comment by martindurant** [comment]
0.3 and 0.4 were both released as noarch
